# GitHub CLI configuration
version: 1
git_protocol: https
prompt: enabled
prefer_editor_prompt: disabled
pager:
editor:
aliases:
    co: pr checkout
browser:
color_labels: disabled
accessible_colors: disabled
accessible_prompter: disabled
spinner: enabled
